# Generated by Django 2.2.13 on 2020-06-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_sfgbedhtnbyed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='sfgbedhtnbyed',
        ),
    ]
